branch-defaults:
  default:
    environment: FMH-APP-dev
global:
  application_name: FMH-APP
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: null
